name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          YOHEM_SECRET_README: ${{ secrets.YOHEM_SECRET_README }}
